### ISSUE TITLE
missing repository 

### ISSUE THREAD

**Issue by chrisfromsoup** [tssgery/nzbapp#7]
I couldn't get this to compile due to the missing repository.

**Comment by tssgery** [comment]
I haven't kept up with turnkeylinux so am not sure if this still works completely

If you're referring to the missing aceshome repo, you actually do not need it. Feel free to modify the source before building or clone/fix.

**Comment by chrisfromsoup** [comment]
Thank you for your reply.  I removed the file 10aceshome and it went a little further, but did not compile still.  I tried some other things, but those didn't work either. Unfortunately, I'm out of my depth here.  Thank you for putting this out there.  I'd really like to use it, but I don't know how.

**Comment by tssgery** [comment]
ok, I'll have a quick look and see if I can get it going again. I'll also upgrade it to the latest couchpotato and sabnzbd, and move from sickbeard to sickrage as it's seeing more development these days.

**Comment by tssgery** [comment]
Updated the patch to work with turnkey 14.1, commit id of f991077a9d70fdc27b9e27984a2bd488bc3fada1

**Comment by chrisfromsoup** [comment]
Awesome!  Thanks so much! Compiling it right now.
